# Generated by Django 5.2 on 2025-04-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.AddField(
            model_name='forum',
            name='global_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='global_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
