# Generated by Django 5.2 on 2025-04-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField()),
            ],
        ),
    ]
